name: CI

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4  

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install project in development mode
        run: pip install -e .

      - name: Run tests
        run: pytest --verbose

      - name: Notify Telegram
        uses: appleboy/telegram-action@v1
        with:
          token: ${{ secrets.PytestBot }}
          chat_id: "946878017"
        if: always() 
