name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-notify:
    runs-on: ubuntu-22.04

    steps:
      # Шаг 1: Получение кода
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Настройка Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      # Шаг 4: Запуск тестов с сохранением результата
      - name: Run tests and capture output
        id: tests
        run: |
          pytest --verbose > test_results.log 2>&1 || echo "Tests failed"
          echo "results=$(cat test_results.log)" >> $GITHUB_OUTPUT
          echo "status=$?" >> $GITHUB_OUTPUT

      # Шаг 5: Отправка уведомления в Telegram
      - name: Notify Telegram with test results
        uses: appleboy/telegram-action@v1
        with:
          token: ${{ secrets.PYTESTBOT}}
          chat_id: "946878017"
          message: |
            ${{ job.status }}: Тесты завершены
            Репозиторий: ${{ github.repository }}
            Ветка: ${{ github.ref }}
            
            ${{ fromJSON('{"0":"✅ Все тесты прошли успешно","1":"❌ Обнаружены ошибки в тестах"}')[steps.tests.outputs.status] }}
            
            Последние результаты:
            ${{ format('{0}', steps.tests.outputs.results) }}

            Подробности: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        if: always()
