name: Python CI with Telegram Notifications

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests and capture status
        id: pytest
        run: |
          # Запускаем тесты и сохраняем результат
          pytest --verbose > pytest.log 2>&1
          TEST_STATUS=$?
          
          # Фильтруем важные строки
          grep -E 'FAILED|ERROR|passed' pytest.log > filtered_results.log
          
          # Сохраняем результаты
          echo "status=$TEST_STATUS" >> $GITHUB_OUTPUT
          echo "results<<EOF" >> $GITHUB_OUTPUT
          cat filtered_results.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
    
          exit $TEST_STATUS

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v1.0.0
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            ${{ fromJSON('{"0":"Тесты прошли успешно","1":"Тесты не прошли"}')[steps.pytest.outputs.status] }}
            
            Результаты:
            ```
            ${{ steps.pytest.outputs.results }}
            ```
            
          
        if: always()
