name: Python CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests and process output
        id: pytest
        run: |
          # Запускаем тесты и сохраняем результат в файл
          pytest --verbose > pytest_output.log 2>&1 || echo "Tests failed"
          
          # Очищаем вывод от лишней информации
          grep -E 'FAILED|ERROR|passed' pytest_output.log > cleaned_output.log
          
          # Сохраняем статус выполнения (0 - успех, 1 - ошибка)
          echo "status=$?" >> $GITHUB_OUTPUT
          
          # Сохраняем очищенный вывод
          echo "results<<EOF" >> $GITHUB_OUTPUT
          cat cleaned_output.log >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Notify Telegram
        uses: appleboy/telegram-action@master
        with:
          token: ${{7214927057:AAF-6jsllfALqjmdkfFsDAO58SU8ehQXAWc}}
          to:  ${{946878017}}
          message: |
            ${{ fromJSON('{"0":"Все тесты прошли успешно","1":" Обнаружены ошибки в тестах"}')[steps.pytest.outputs.status] }}
            
            Результаты тестов:
            ```
            ${{ steps.pytest.outputs.results }}
            ```
            
            Подробности: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        if: always()
