name: Python CI with Telegram Notifications

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests and capture output
        id: pytest
        continue-on-error: true  # Продолжаем workflow даже при ошибке тестов
        run: |
          # Запускаем тесты и сохраняем вывод
          pytest --verbose > pytest_output.log 2>&1 || echo "Pytest завершился с ошибкой"
          TEST_STATUS=$?
          
          # Формируем отчет
          echo "=== Краткая
          
