name: Python CI with Telegram Notifications

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-and-notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Run tests
        id: pytest
        run: |
          pytest --verbose > pytest.log 2>&1 || echo "Tests failed"
          echo "status=$?" >> $GITHUB_OUTPUT
          echo "results<<EOF" >> $GITHUB_OUTPUT
          cat pytest.log | grep -E 'FAILED|ERROR|passed' >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v1.0.0
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}  # Должен быть задан в Secrets
          to: ${{ secrets.TELEGRAM_CHAT_ID }}      # Должен быть задан в Secrets
          message: |
            ${{ fromJSON('{"0":"✅ Тесты прошли успешно","1":"❌ Тесты не прошли"}')[steps.pytest.outputs.status] }}
            
            Результаты:
            ```
            ${{ steps.pytest.outputs.results }}
            ```
            
            Ссылка на выполнение:
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        if: always()
